version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_pwd
      MYSQL_DATABASE: dbtest
      MYSQL_USER: dbtest
      MYSQL_PASSWORD: dbtest_pwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: